### ISSUE TITLE
update to new swagger spec

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-clients-route-optimization#1]
related to https://github.com/graphhopper/directions-api-java-client/issues/8

**Comment by oblonski** [comment]
What will our policy be here to update this client? Or should we leave this to the user? If so, we should not offer this client via Maven Central. Since we offer this, we should generate a new client after every API change. What do you think, @karussell?

**Comment by karussell** [comment]
Our aim should be an up-to-date client in maven central. But as a maven central release is not fully 'automatable' (at least how I do this via sonatype) we have to do some kind of compromise. And the user always has the possibility to ask us or build it on its own.

**Comment by oblonski** [comment]
Ok! 👍 
Would you mind to update this to the new spec? Thanks, @karussell

**Comment by oblonski** [comment]
BTW: Do I need to download swagger for myself to generate a new client with this script?

**Comment by karussell** [comment]
Yes. And location inside the repository at `swagger-codegen/`. Should we include it here?

**Comment by oblonski** [comment]
Hmm. It would be quite comfortable for the user to just clone this and do `create.sh java` to get the latest client. What do you think? Otherwise, we should add a description of how to get and install swagger.

**Comment by karussell** [comment]
If we include it hear we need a simple procedure to update the swagger code as well. And this is only easy & simple with a sub module which I wanted to avoid for now. But yes, we can add it as a submodule and include build instructions for this as well here.

**Comment by oblonski** [comment]
We can leave it for now and just add a description of how to get things prepared to run this create.sh script.

**Comment by oblonski** [comment]
If you would add the desc, I can test it :)?

**Comment by karussell** [comment]
Updated the script to automatically download the jar. So no need to update the Readme and easier installation :). Please let me know if this works for you.

**Comment by oblonski** [comment]
Great. Thanks. I get this when trying `./create.sh java`
```
bash-3.2$ ./create.sh java
./create.sh: line 9: wget: command not found
java -jar swagger-codegen-cli-2.1.6.jar generate -i https://graphhopper.com/api/1/vrp/swagger.json -l java -c java.json -o ./java
Error: Unable to access jarfile swagger-codegen-cli-2.1.6.jar
```

**Comment by oblonski** [comment]
This has to do with my mac: https://coolestguidesontheplanet.com/install-and-configure-wget-on-os-x/

**Comment by oblonski** [comment]
Should I get `wget` then or can we just use `curl` if wget is not available?

**Comment by karussell** [comment]
Please try again, added a curl fallback

**Comment by karussell** [comment]
Fixed via: https://github.com/graphhopper/directions-api-clients-route-optimization/commit/d119d7a33626d083a9ab9fb45b0bb9eeabe35756

**Comment by oblonski** [comment]
Hurray! It works 👍 . Thanks @karussell
