### ISSUE TITLE
Route optimization API

### ISSUE THREAD

**Issue by hariomenkel** [graphhopper/directions-api-clients-route-optimization#10]
Hi,

I set up the graphhopper server locally and I wonder if I can query the route optimization API on this server or if it is neccessary to pay for your route optimizazion service.

Kind regards

**Comment by karussell** [comment]
Please see [here](https://graphhopper.com/#open-source-comparison) for an overview what is open source and what not. The 'graphhopper server' you are (probably) referring to is the [graphhopper routing engine](https://github.com/graphhopper/graphhopper) which just provides the routes from A-B.
