### ISSUE TITLE
Reserved Keyword Break

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/directions-api-clients-route-optimization#12]
When generating a Java client from this swagger I receive the following warning:
`[main] WARN io.swagger.codegen.DefaultCodegen - Break (reserved word) cannot be used as model name. Renamed to ModelBreak`. Not really an issue, just wanted to let you know, in case you haven't seen that. So eventually it might make sense to rename Break?

**Comment by karussell** [comment]
Yes, [we are aware of this](https://github.com/swagger-api/swagger-codegen/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20author%3Akarussell%20) ;)

Renaming is not possible without breaking existing clients.

**Comment by boldtrn** [comment]
Ah ok, I was just wondering :).
