### ISSUE TITLE
Tweak necessary for autogenerated Ruby client

### ISSUE THREAD

**Issue by bizlift** [graphhopper/directions-api-clients-route-optimization#3]
The autogenerated Swagger client for ruby works fine in my rails app.  The only fix I had to do was on models/solution.rb line 49:

from
`        :'unassigned' => :'Solution_unassigned'`
to
`        :'unassigned' => :'SolutionUnassigned'`

Thank you providing these clients.

**Comment by karussell** [comment]
Thanks! As we auto-created this via Swagger, maybe this is a bug in the swagger code. Just for reference [here is the line](https://github.com/graphhopper/directions-api-clients-route-optimization/blob/master/ruby/lib/graphhopper/models/solution.rb#L49)

**Comment by karussell** [comment]
This seems to be fixed when creating the client with the latest stable swagger codegen. Please let me know if the new client runs without problem :)

**Comment by bizlift** [comment]
New swagger build fixed it and client runs great.  Thank you for quick fix!

**Comment by karussell** [comment]
Thank you for reporting!
