### ISSUE TITLE
Activity distance is missing

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-clients-route-optimization#8]
We need to adjust once again the swagger spec and recreate the clients

**Comment by oblonski** [comment]
@karussell I updated the swagger file. Would you mind to upload it and update the clients? Thanks a lot.

**Comment by karussell** [comment]
Sure

**Comment by karussell** [comment]
Fixed with https://github.com/graphhopper/directions-api-clients-route-optimization/commit/4b716298cc603e4efd34c75268bc2774620309af

**Comment by oblonski** [comment]
the swagger spec I can access via https://graphhopper.com/api/1/vrp/swagger.json is still an old one. did you upload the latest from the corresponding prj folder?

**Comment by oblonski** [comment]
generated clients seem to be based on the latest swagger spec :)

**Comment by karussell** [comment]
Probably the browser caches this, try refresh

**Comment by oblonski** [comment]
ok. worked. thanks.
